services:
  redis:
    image: redis:latest
    container_name: guesser_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

  app:
    container_name: "guesser_app"
    build: .
    depends_on:
      - db
    working_dir: /src
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn market_main:app --host 0.0.0.0 --port 8000'
    networks:
      - guesser-network

  db:
    image: postgres:latest
    container_name: guesser_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - guesser-network

  nginx:
    image: nginx:latest
    container_name: guesser_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/root/Matcher/static/
      - /etc/letsencrypt/live/matcher-market.shop/fullchain.pem:/etc/letsencrypt/live/matcher-market.shop/fullchain.pem
      - /etc/letsencrypt/live/matcher-market.shop/privkey.pem:/etc/letsencrypt/live/matcher-market.shop/privkey.pem
    networks:
      - guesser-network

  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - guesser-network

volumes:
  postgres-data:

networks:
  guesser-network:
    driver: bridge
