services:
  redis:
    image: redis:latest
    container_name: matcher_redis
    deploy:
      resources:
        limits:
          memory: 256M
    command: ["redis-server", "--maxmemory", "200mb", "--maxmemory-policy", "allkeys-lru"]
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - matcher-network

  app:
    container_name: matcher_site
    build: .
    depends_on:
      - db
      - redis
    working_dir: /src
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn market_main:app --host 0.0.0.0 --port 8000'
    networks:
      - matcher-network

  db:
    image: postgres:latest
    container_name: matcher_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - matcher-network

  nginx:
    image: nginx:latest
    container_name: matcher_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/root/Matcher/static/
      - /etc/letsencrypt/live/matcher-market.shop/fullchain.pem:/etc/letsencrypt/live/matcher-market.shop/fullchain.pem
      - /etc/letsencrypt/live/matcher-market.shop/privkey.pem:/etc/letsencrypt/live/matcher-market.shop/privkey.pem
    networks:
      - matcher-network

  bot:
    container_name: matcher_bot
    build: .
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - DB_HOST=db
    networks:
      - matcher-network

  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    container_name: matcher_rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_PORT}:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    networks:
      - matcher-network


volumes:
  postgres-data:
  rabbitmq_data:

networks:
  matcher-network:
    driver: bridge
